# NumPy Practice Questions

**Instructions:** Dear Students Each question is self‑explanatory. Read the markdown prompt and write the code in the cell below it where marked `# answer here`. Keep solutions simple and focused on the asked concept.

- Q1–Q30: Single-topic questions in sequence (basics → indexing → operations → aggregations → reshaping/broadcasting → utilities).

- Q31–Q35: Multi‑concept (combine 2–3 ideas you practiced).

- Q36–Q40: Use a single dataset loaded via **pandas** and perform **NumPy** operations on it. The file `students_scores.csv` is already available in the same folder as this notebook.


### Q1. Create a 1D NumPy array from the Python list `[1, 2, 3, 4, 5]` and print its type and contents.

In [2]:
# answer here
import numpy as np
import pandas as pd


In [3]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


### Q2. Create a 2D NumPy array from `[[1, 2, 3], [4, 5, 6]]` and print its `shape` and `ndim`.

In [4]:
# answer here
Arr = np.array([[1,2,3],
              [4,5,6]])
print(Arr)
print(Arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


### Q3. Create an array of 6 zeros and print it.

In [5]:
# answer here
zeros_arr = np.zeros(6)
print(zeros_arr)

[0. 0. 0. 0. 0. 0.]


### Q4. Create an array of 5 ones (float) and print it.

In [6]:
# answer here
ones_arr = np.ones(5)
print(ones_arr)

[1. 1. 1. 1. 1.]


### Q5. Use `np.arange` to create an array from 2 to 14 (inclusive of 2, exclusive of 14) with a step of 2 and print it.

In [7]:
# answer here
np.arange(2,14,2)

array([ 2,  4,  6,  8, 10, 12])

### Q6. Use `np.linspace` to create 5 evenly spaced values from 0 to 1 and print them.

In [8]:
# answer here
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Q7. Create an integer array `[10, 20, 30]` then convert it to `float` dtype and print both arrays.

In [9]:
# answer here
int_arr = np.array([10,20,30])
float_arr = int_arr.astype('float')
print(int_arr)
print(float_arr)

[10 20 30]
[10. 20. 30.]


### Q8. Create an array of 12 numbers from 0 to 11 and reshape it to `3x4`; print the reshaped array.

In [10]:
# answer here
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Q9. For the array `a = np.array([[1,2,3],[4,5,6]])`, print `a.shape`, `a.ndim`, and `a.size`.

In [11]:
# answer here
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.ndim)
print(a.size)

(2, 3)
2
6


### Q10. For the array `a = np.array([1,2,3], dtype=np.int32)`, print `a.dtype` and `a.itemsize`.

In [12]:
# answer here
a = np.array([[1,2,3],[4,5,6]])

print(a.dtype)
print(a.itemsize)


int64
8


### Q11. Given `arr = np.array([10, 20, 30, 40, 50])`, print the first element, last element, and the element at index 2.

In [13]:
# answer here
A = np.array([10,20,30,40,50])
print(A[0])
print(A[-1])
print(A[2])

10
50
30


### Q12. Given `arr = np.array([5, 10, 15, 20, 25])`, use negative indexing to print the last two elements.

In [14]:
# answer here
B = np.array([5,10,15,20,25])
B[-2:]

array([20, 25])

### Q13. Given `arr = np.array([0,1,2,3,4,5,6,7,8,9])`, print the slice from index 2 to 7 (exclusive).

In [15]:
# answer here
C = np.arange(10)
C[2:7]

array([2, 3, 4, 5, 6])

### Q14. Given `m = np.arange(1,13).reshape(3,4)`, print the second row and the third column (as 1D slices).

In [16]:
# answer here
m = np.arange(1,13).reshape(3,4)
print(m)
print("Second row", m[1,:])
print("Third Columns",m[:,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Second row [5 6 7 8]
Third Columns [ 3  7 11]


### Q15. Given `m = np.arange(1,13).reshape(3,4)`, print the submatrix containing rows 0 to 1 and columns 1 to 3.

In [17]:
# answer here
M = np.arange(1,13).reshape(3,4)
print(M)
print("*"*50)
M[0:2,1:4]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
**************************************************


array([[2, 3, 4],
       [6, 7, 8]])

### Q16. Given `arr = np.arange(1,11)`, create a boolean mask for even numbers and print the even elements.

In [18]:
# answer here
arr = np.arange(1,11)
mask = arr%2 == 0
print(arr)
print(mask)
print(arr[mask])

[ 1  2  3  4  5  6  7  8  9 10]
[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]


### Q17. Given `arr = np.arange(1,11)`, set all odd elements to `-1` (modify in place) and print the result.

In [19]:
# answer here
arr = np.arange(1,11)
arr[arr%2 != 0] = -1
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1 10]


### Q18. Given `arr = np.array([1,2,3])`, add `5` to every element and print the result (element‑wise).

In [20]:
# answer here
arr1 = np.array([1,2,3])
arr2= np.array([5])
res_arr = arr1 + arr2
res_arr

array([6, 7, 8])

### Q19. Given `a = np.array([1,2,3])` and `b = np.array([4,5,6])`, print `a + b` and `a * b` (element‑wise).

In [21]:
# answer here
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print(a * b)

[5 7 9]
[ 4 10 18]


### Q20. Given `a = np.array([1,2,3])` and `b = np.array([[10],[20],[30]])`, use broadcasting to compute `a + b` and print it.

In [22]:
# answer here
a = np.array([1,2,3])
b = np.array([[10],[20],[30]])
res = a + b
print(res)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


### Q21. Given `arr = np.array([3, 7, 2, 9, 5])`, print its `sum`, `mean`, `min`, and `max`.

In [23]:
# answer here
a = np.array([3,5,2,9,5])
print(sum(a))
print(a.mean())
print(min(a))
print(max(a))

24
4.8
2
9


### Q22. Given `m = np.arange(1,13).reshape(3,4)`, print the sum along axis 0 and along axis 1.

In [24]:
# answer here
m = np.arange(1,13).reshape(3,4)
print(m)
print("*"*50)
print(m.sum(axis=0))
print("*"*50)
print(m.sum(axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
**************************************************
[15 18 21 24]
**************************************************
[10 26 42]


### Q23. Given `arr = np.array([10, 20, 5, 40, 25])`, print the indices of the `max` and `min` elements using `np.argmax` and `np.argmin`.

In [25]:
# answer here
array =  np.array([10,20,5,40,25])
print("Indix of maximum element",array.argmax())
print("Index of minimum element",array.argmin())


Indix of maximum element 3
Index of minimum element 2


### Q24. Given `arr = np.array([3, 3, 1, 2, 2, 2, 5])`, print the sorted array and the unique values using `np.unique`.

In [26]:
# answer here
arr = np.array([3,3,12,2,2,5])
print(np.sort(arr))
print(arr)
print(np.unique(arr))

[ 2  2  3  3  5 12]
[ 3  3 12  2  2  5]
[ 2  3  5 12]


### Q25. Given `arr = np.array([9, 1, 5, 3, 7])`, sort it in ascending order and print the result (do not modify original).

In [27]:
# answer here
arr = np.array([9,1,5,3,7])
sorted_arr = np.sort(arr)
print("Original Arr:",arr)
print("Sorted Arr:",sorted_arr)

Original Arr: [9 1 5 3 7]
Sorted Arr: [1 3 5 7 9]


### Q26. Given `a = np.array([1,2,3])` and `b = np.array([4,5,6])`, horizontally concatenate them and print the result.

In [28]:
# answer here
a = np.array([1,2,3])
b = np.array([4,5,6])

res = np.hstack((a,b))
res

array([1, 2, 3, 4, 5, 6])

### Q27. Given `A = np.array([[1,2],[3,4]])` and `B = np.array([[5,6],[7,8]])`, stack them vertically and print the result.

In [29]:
# answer here
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

res = np.concatenate((A,B), axis=0)
res

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### Q28. Given `arr = np.arange(1,13)`, split it into 3 equal parts and print each part.

In [30]:
# answer here
arr = np.arange(1,13).reshape(4,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Q29. Set a random seed (e.g., 42), generate 5 random integers from 0 to 9 using `np.random.randint`, and print them.

In [31]:
# answer here
np.random.seed(42)
arr = np.random.randint(0,10, size=5)
arr

array([6, 3, 7, 4, 6])

### Q30. Given `arr = np.array([-3, 1, -1, 4, -2, 5])`, use `np.where` to replace negative values with `0` and print the new array.

In [32]:
# answer here
arr = np.array([-3, 1, -1, 4, -2, 5])
new_arr = np.where(arr<0,0,arr)
new_arr

array([0, 1, 0, 4, 0, 5])

### Q31. Create a 3D array of shape `(2, 3, 4)` using `np.arange` then compute the mean along axis 2 and print the result.

In [33]:
# answer here
arr =  np.arange(24).reshape(2,3,4)
print("Original array",arr)
print(arr.mean(axis=2))

Original array [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 1.5  5.5  9.5]
 [13.5 17.5 21.5]]


### Q32. Create an array from `[5, 10, 15, 20, 25]`, slice out `[10, 15, 20]`, then normalize that slice to range 0–1 using min‑max formula and print it.

In [34]:
# answer here
arr = np.array([5,10,15,20,25])
res = arr[1:4]
print(arr)
print("*"*60)
print(res)
print("*"*60)
norm_array = (res - res.min())/(res.max() - res.min())
norm_array


[ 5 10 15 20 25]
************************************************************
[10 15 20]
************************************************************


array([0. , 0.5, 1. ])

### Q33. Create two 1D arrays `a=[1,2,3]` and `b=[4,5,6]`; compute the dot product and also form a `3x2` matrix from `a` and `b` and print both results.

In [35]:
# answer here
a = np.array([1,2,3])
b = np.array([4,5,6])
dot_product =np.dot(a,b)
dot_product
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

### Q34. Create an array of 12 values (1–12), reshape it to `3x4`, then count how many values are greater than `6` and print the count.

In [36]:
# answer here
arr = np.arange(1,13).reshape(3,4)
res = np.sum(arr>6)
print(arr)
print("Count of values in arr > 6 are: ", res)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Count of values in arr > 6 are:  6


### Q35. Create an array from 0–9; replace all odd numbers with `-1` *except* keep the first and last elements unchanged; print the final array.

In [37]:
# answer here
arr = np.arange(10)
res = np.where((arr%2 != 0) & (arr != arr[0]) & (arr != arr[-1]),-1,arr)
res

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8,  9])

### Dataset for Q36–Q40

A CSV file **`students_scores.csv`** is already placed in this folder (Link-https://drive.google.com/file/d/1B7zDahhmQzXkQmvskS27H07B4Xftf9xA/view?usp=sharing).  

Columns: `id, math, english, science` (10 students). Use **pandas** to import the file and then perform **NumPy** operations.


### Q36. Import `students_scores.csv` as a pandas DataFrame `df`. Then convert the `math`, `english`, and `science` columns to separate NumPy arrays and print their shapes.

In [38]:
# answer here
df = pd.read_csv('students_scores.csv')
print(df.columns)
m_arr = np.array([df['math']])
e_arr =  np.array([df['english']])
s_arr =  np.array([df['science']])
print(m_arr.shape)
print(e_arr.shape)
print(s_arr.shape)

Index(['id', 'math', 'english', 'science'], dtype='object')
(1, 10)
(1, 10)
(1, 10)


### Q37. Using NumPy on the arrays from Q36, compute the mean score of each subject (math, english, science) and print them.

In [39]:
# answer here
print(m_arr.mean())
print(e_arr.mean())
print(s_arr.mean())

70.3
69.5
70.1


### Q38. Using NumPy, compute each student’s **total score** (math + english + science) and print the `id` of the student with the highest total.

In [56]:
# answer here
total = m_arr + e_arr + s_arr
res = total.argmax()
res
id = np.array(df['id'])
print(id)
print("Highest Student ID for total marks", id[res])

['S01' 'S02' 'S03' 'S04' 'S05' 'S06' 'S07' 'S08' 'S09' 'S10']
Highest Student ID for total marks S03


### Q39. Using NumPy, standardize the `math` scores to **z-scores**: `(x - mean) / std` and print the first 5 standardized values.

In [60]:
# answer here
math_Score = df['math'].values
math_Score
z_scores = (math_Score - np.mean(math_Score))/np.std(math_Score)
print(z_scores[:5])

[ 0.53032869 -0.98489614  1.21906724 -1.74250855  1.49456267]


In [42]:
# this is how you can approach question number 39
# dont fear about std(standard deviation , just google it and you understand its simple, else you can connect for doubts)


import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv("students_scores.csv")

# Extract math column as NumPy array
math_scores = df["math"].values

# Compute z-scores
z_scores = (math_scores - np.mean(math_scores)) / np.std(math_scores)

# Print first 5 standardized values
print(z_scores[:5])


[ 0.53032869 -0.98489614  1.21906724 -1.74250855  1.49456267]


### Q40. Using NumPy logical operations, count how many students scored **≥ 70 in all three subjects** and print that count.

In [62]:
# answer here


id  math  english  science
0  S01    78       65       72
1  S02    56       70       60
2  S03    88       81       90
3  S04    45       55       48
4  S05    92       76       85
5  S06    67       62       71
6  S07    73       80       66
7  S08    59       58       64
8  S09    84       79       88
9  S10    61       69       57

In [69]:
passed = np.where((df['math'].values > 70) & (df['english'].values > 70) & (df['science'].values > 70))

In [71]:
np.sum(passed)
passed

(array([2, 4, 8]),)

In [74]:
passed_all = (m_arr >= 70) & (e_arr>= 70) & (s_arr>= 70)
print(passed_all)

count = np.sum(passed_all)

print("Students who scored ≥70 in all subjects:", count)

[[False False  True False  True False False False  True False]]
Students who scored ≥70 in all subjects: 3
